### PR TITLE
Add supply kontainers in KIS SC-62 form factor

### PR DESCRIPTION
**Pull request by Wyzard256**
These two new parts are based on the existing MK-V Supply Redi-Pak and MK-V Saddle Tank, morphed into the form factor of the SC-62 storage container from KIS.  Like the SC-62, they can be carried on a kerbal's back and mounted (even by non-engineers) on the SM-62 container mount.  Capacity, mass, and cost have been scaled down to 80% of the corresponding MK-V parts, to match the SC-62's 1000L volume.

This form factor fits very nicely on the Akita rover bed, as well as on the sides of the MKS Ranger trusses.  I recently submitted ihsoft/KIS#191 to help engineers install the SM-62 container mount in those places, which allows non-engineers to mount and dismount the containers.  Even without that, though, engineers can attach the containers directly.

I'm hoping that these parts can become the Akita's equivalent of the Karibou's flatbed cargo crates and tanks.  You can also fit nine of them on a Karibou flatbed, though it's a tight fit (they clip slightly).

Local logistics reduces the need for carrying containers full of resources around, but there are still a few use-cases that I can think of for these parts:
* Transporting resources to/from a vessel that's outside the 150m local logistics range, such as a lander that came down a little too far away.
* Moving storage *capacity* (as opposed to actual resources) around — e.g. reconfigure a vessel from solid to liquid storage just by swapping out the containers mounted on it.  Thanks to the SM-62 container mount, non-engineers can do this.

I'm not an artist and I can't make custom models for these new parts, so for now they re-use the KIS container's model.  I don't really think they ought to be released like that, but I figured I'd contribute the part configs in case someone's inclined to make models to go with them.

### CODE REVIEW

**Comment by Wyzard256** [comment]
Since a picture is worth a thousand words:

screenshot

**Comment by Wyzard256** [comment]
I took a shot at making models for these parts, by combining the bottom part of the KIS container with elements of existing USI kontainers.  Here's an updated screenshot:

mountable

(I only checked in the `.mu` files since that seems to be the established thing to do, but I'll be happy to send you the original Blender files and Unity project if you want them.)

A few notes:

* The bottom part of each model is based on the KIS SC-62 container.  I've gotten the OK from Winn75 (who made that model) to release this derivative.
* Since these parts depend on the player having KIS installed, I'm using "texture" attributes in the `.cfg` to load the texture from the KIS folder.  But KSP requires a valid texture alongside the `.mu` even if it later gets overridden by a "texture" attribute in the `.cfg`, so I had to add a pair of 1-pixel placeholder textures.
* The SK-62 kontainer uses a Karibou texture.  I added a copy of Karibou's `RoverKontainers.dds` file here, rather than referencing it with a "texture" attribute, since not everyone who uses Kontainers may have Karibou installed.

Feedback/criticism is welcome, and feel free to make further changes of your own.

**Comment by Wyzard256** [comment]
I've adjusted the collider on base of these containers to avoid clipping into the container mount, in the same way that ihsoft/KIS#200 recently did for the KIS container.

However, I'm working on some better models for these parts.  The current models were designed specifically to re-use existing textures, but the shape at the base is a little awkward as a result, and I ended up having to check in a copy of a Karibou texture, as well as a dummy placeholder for a KIS texture.  I don't like that, so I'm making replacement models with textures of their own.  (I'm inexperienced at this, though, so it's slow going.)

**Comment by BobPalmer** [comment]
Awesome stuff!

Should this go in as-is, or should I hold off?

**Comment by Wyzard256** [comment]
Up to you, but I'd suggest holding off for now.  I have the liquids tank basically done, I think, and the solids kontainer is modeled and UV-mapped but I've just started on its texture.  It's my first real attempt at texturing, so it'll probably take a lot of trial and error to come up with something that looks at least half-decent, but I'm hoping to finish it sometime this weekend.  (I've been watching your recent Twitch streams to learn techniques, btw.)

The new models still look very similar to the old ones overall — the big difference is that instead of having a piece of the KIS container tacked onto the bottom, the mounting bracket shape is integrated into the part so it looks more natural.  I'll add some screenshots later.

**Comment by Wyzard256** [comment]
Here's how the new liquids tank looks:
new-tank

And the untextured new solids kontainer (which is basically a hybrid of the KIS container and the Karibou crate):
new-crate

I'm planning to put caution stripes on it in the same places as on the Karibou crate, but I'll make the rest look a bit different.  Suggestions & feedback are welcome, though.

**Comment by BobPalmer** [comment]
Looks great!  Doing a release now so we'll hold off on these till you give me the green light,

**Comment by Wyzard256** [comment]
Well, I didn't finish up last weekend like I'd hoped to, but here's what I came up with for the solids kontainer:

sk-62

I tried to combine visual elements of both the KIS container (monochromatic, light/dark contrast, triangular arrows) and existing USI kontainers (corrugated sides and yellow paint markings).  The dark inset panels are normal-mapped in the way as the big USI shipping crates.

These new models are still partially based on the KIS container, so I've contacted Winn75 again to ask for the OK to release them.  Once he gets back to me (assuming he says yes like last time), I'll check them in.  So, not ready quite yet.

BTW, I don't know what fonts you used for text on other USI parts, so I used [Noto Sans](https://www.google.com/get/noto/), a free font provided by Google.  I'd like to be consistent, though, so if you send me a font that you prefer (or point me to where I can get it), I'll change the texture to use it.

**Comment by BobPalmer** [comment]
These look beautiful!  font is fine (I use a few different ones myself based on the text and size).

**Comment by Wyzard256** [comment]
Thanks!  This wasn't ready to merge yet, though — I haven't actually checked in the new files, because I'm waiting for Winn75 (who made the KIS container model) to give me the OK to release them (since they're partly based on it).

**Pull request merged**
